const REGISTER = 'REGISTER'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const GETTEAMS='GETTEAMS'
const GETTEAMBYLOGINUSER='GETTEAMBYLOGINUSER'
const GETMEMBERBYTEAM='GETMEMBERBYTEAM'


export {
    REGISTER,
    LOGIN,
    LOGOUT,
    GETTEAMS,
    GETTEAMBYLOGINUSER,
    GETMEMBERBYTEAM
}